/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author UsuarioN°1000
 */
public class Plataforma extends javax.swing.JFrame {

    /**
     * Creates new form LeyOhm
     */
    public Plataforma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cable2 = new javax.swing.JProgressBar();
        luz = new javax.swing.JLabel();
        pila = new javax.swing.JButton();
        cable11 = new javax.swing.JProgressBar();
        luz3 = new javax.swing.JLabel();
        luz2 = new javax.swing.JLabel();
        cable14 = new javax.swing.JProgressBar();
        cable8 = new javax.swing.JProgressBar();
        cable9 = new javax.swing.JProgressBar();
        cable10 = new javax.swing.JProgressBar();
        cable = new javax.swing.JProgressBar();
        cable5 = new javax.swing.JProgressBar();
        cable6 = new javax.swing.JProgressBar();
        cable7 = new javax.swing.JProgressBar();
        cable3 = new javax.swing.JProgressBar();
        cable4 = new javax.swing.JProgressBar();
        cable12 = new javax.swing.JProgressBar();
        cable13 = new javax.swing.JProgressBar();
        calcular = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cable2.setBackground(new java.awt.Color(102, 102, 102));
        cable2.setForeground(new java.awt.Color(255, 255, 0));
        getContentPane().add(cable2, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 53, 162, 6));

        luz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icono2.png"))); // NOI18N
        getContentPane().add(luz, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 186, -1, 55));

        pila.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/pila.png"))); // NOI18N
        pila.setBorderPainted(false);
        pila.setContentAreaFilled(false);
        pila.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pila.setFocusPainted(false);
        getContentPane().add(pila, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 161, 96, -1));

        cable11.setBackground(new java.awt.Color(102, 102, 102));
        cable11.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(cable11, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 352, 165, 6));

        luz3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icono2.png"))); // NOI18N
        getContentPane().add(luz3, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 186, -1, 55));

        luz2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icono2.png"))); // NOI18N
        getContentPane().add(luz2, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 186, -1, 55));

        cable14.setBackground(new java.awt.Color(102, 102, 102));
        cable14.setForeground(new java.awt.Color(255, 255, 0));
        cable14.setOrientation(1);
        getContentPane().add(cable14, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 248, 6, 101));

        cable8.setBackground(new java.awt.Color(102, 102, 102));
        cable8.setForeground(new java.awt.Color(102, 102, 102));
        cable8.setOrientation(1);
        getContentPane().add(cable8, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 247, 6, 102));

        cable9.setBackground(new java.awt.Color(102, 102, 102));
        cable9.setForeground(new java.awt.Color(102, 102, 102));
        cable9.setOrientation(1);
        getContentPane().add(cable9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 247, 6, 102));

        cable10.setBackground(new java.awt.Color(102, 102, 102));
        cable10.setForeground(new java.awt.Color(102, 102, 102));
        cable10.setOrientation(1);
        getContentPane().add(cable10, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 247, 6, 102));

        cable.setBackground(new java.awt.Color(102, 102, 102));
        cable.setForeground(new java.awt.Color(255, 255, 0));
        cable.setOrientation(1);
        getContentPane().add(cable, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 65, 6, 90));

        cable5.setBackground(new java.awt.Color(102, 102, 102));
        cable5.setForeground(new java.awt.Color(102, 102, 102));
        cable5.setOrientation(1);
        getContentPane().add(cable5, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 65, 6, 115));

        cable6.setBackground(new java.awt.Color(102, 102, 102));
        cable6.setForeground(new java.awt.Color(102, 102, 102));
        cable6.setOrientation(1);
        getContentPane().add(cable6, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 65, 6, 115));

        cable7.setBackground(new java.awt.Color(102, 102, 102));
        cable7.setForeground(new java.awt.Color(102, 102, 102));
        cable7.setOrientation(1);
        getContentPane().add(cable7, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 65, 6, 115));

        cable3.setBackground(new java.awt.Color(102, 102, 102));
        cable3.setForeground(new java.awt.Color(255, 255, 0));
        getContentPane().add(cable3, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 53, 198, 6));

        cable4.setBackground(new java.awt.Color(102, 102, 102));
        cable4.setForeground(new java.awt.Color(255, 255, 0));
        getContentPane().add(cable4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 53, 157, 6));

        cable12.setBackground(new java.awt.Color(102, 102, 102));
        cable12.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(cable12, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 352, 198, 6));

        cable13.setBackground(new java.awt.Color(102, 102, 102));
        cable13.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(cable13, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 352, 157, 6));

        calcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/calc.png"))); // NOI18N
        calcular.setBorderPainted(false);
        calcular.setContentAreaFilled(false);
        calcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        calcular.setFocusPainted(false);
        getContentPane().add(calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, -1, 80));

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("R1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 165, -1, -1));

        jLabel2.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("R2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 165, -1, -1));

        jLabel3.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("R3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(556, 165, -1, -1));

        jLabel4.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("I1");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 247, -1, -1));

        jLabel5.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("I2");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 247, -1, -1));

        jLabel6.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("I3");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 247, -1, -1));

        jLabel7.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("I total");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 248, -1, -1));

        jLabel8.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("V1");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        jLabel9.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("V2");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, -1, -1));

        jLabel10.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("V3");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, -1, -1));

        jLabel11.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("R total");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        jLabel12.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("V total");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        jLabel14.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("R total");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        jLabel15.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("V total");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        jLabel16.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("R1");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 165, -1, -1));

        jLabel17.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("R2");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 165, -1, -1));

        jLabel18.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("R3");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(556, 165, -1, -1));

        jLabel19.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("I1");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 247, -1, -1));

        jLabel20.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("I2");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 247, -1, -1));

        jLabel21.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("I3");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 247, -1, -1));

        jLabel22.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("I total");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 248, -1, -1));

        jLabel23.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("V1");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        jLabel24.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("V2");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, -1, -1));

        jLabel25.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("I3");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 247, -1, -1));

        jLabel26.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("R total");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        jLabel27.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("V total");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        jLabel28.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("I2");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 247, -1, -1));

        jLabel29.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("V1");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        jLabel30.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("V2");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, -1, -1));

        jLabel31.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("I total");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 248, -1, -1));

        jLabel32.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("R2");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 165, -1, -1));

        jLabel33.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("R3");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(556, 165, -1, -1));

        jLabel34.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("R1");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 165, -1, -1));

        jLabel35.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("I1");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 247, -1, -1));

        jLabel36.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("R2");
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 165, -1, -1));

        jLabel37.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("R1");
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 165, -1, -1));

        jLabel38.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("R3");
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(556, 165, -1, -1));

        jLabel39.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("I1");
        getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 247, -1, -1));

        jLabel40.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("I2");
        getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 247, -1, -1));

        jLabel41.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("I3");
        getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 247, -1, -1));

        jLabel42.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("R3");
        getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(556, 165, -1, -1));

        jLabel43.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("R1");
        getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 165, -1, -1));

        jLabel44.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("R2");
        getContentPane().add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 165, -1, -1));

        jLabel45.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("I1");
        getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 247, -1, -1));

        jLabel46.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("I2");
        getContentPane().add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 247, -1, -1));

        jLabel47.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("I3");
        getContentPane().add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 247, -1, -1));

        jLabel48.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("R3");
        getContentPane().add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(556, 165, -1, -1));

        jLabel49.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("R2");
        getContentPane().add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 165, -1, -1));

        jLabel50.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("I1");
        getContentPane().add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 247, -1, -1));

        jLabel51.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("I3");
        getContentPane().add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 247, -1, -1));

        jLabel52.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("R1");
        getContentPane().add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 165, -1, -1));

        jLabel53.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("I2");
        getContentPane().add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 247, -1, -1));

        jLabel54.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("R2");
        getContentPane().add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 165, -1, -1));

        jLabel55.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("R1");
        getContentPane().add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 165, -1, -1));

        jLabel56.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("R3");
        getContentPane().add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(556, 165, -1, -1));

        jLabel57.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setText("I1");
        getContentPane().add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 247, -1, -1));

        jLabel58.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("I2");
        getContentPane().add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 247, -1, -1));

        jLabel63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/t.png"))); // NOI18N
        getContentPane().add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 50, 30));

        jLabel64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/t.png"))); // NOI18N
        getContentPane().add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jLabel65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/t.png"))); // NOI18N
        getContentPane().add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jLabel66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/t.png"))); // NOI18N
        getContentPane().add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, -1, -1));

        jLabel67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/t.png"))); // NOI18N
        getContentPane().add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, -1, -1));

        jLabel68.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/t.png"))); // NOI18N
        getContentPane().add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, -1, -1));

        jLabel69.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/t.png"))); // NOI18N
        getContentPane().add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));

        jLabel70.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/t.png"))); // NOI18N
        getContentPane().add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/imagen.jpg"))); // NOI18N
        jLabel13.setPreferredSize(new java.awt.Dimension(686, 428));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Plataforma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Plataforma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Plataforma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Plataforma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Plataforma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JProgressBar cable;
    public javax.swing.JProgressBar cable10;
    public javax.swing.JProgressBar cable11;
    public javax.swing.JProgressBar cable12;
    public javax.swing.JProgressBar cable13;
    public javax.swing.JProgressBar cable14;
    public javax.swing.JProgressBar cable2;
    public javax.swing.JProgressBar cable3;
    public javax.swing.JProgressBar cable4;
    public javax.swing.JProgressBar cable5;
    public javax.swing.JProgressBar cable6;
    public javax.swing.JProgressBar cable7;
    public javax.swing.JProgressBar cable8;
    public javax.swing.JProgressBar cable9;
    public javax.swing.JButton calcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel luz;
    public javax.swing.JLabel luz2;
    public javax.swing.JLabel luz3;
    public javax.swing.JButton pila;
    // End of variables declaration//GEN-END:variables
}
