/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author UsuarioN°1000
 */
public class Plataforma2 extends javax.swing.JFrame {

    /**
     * Creates new form Plataforma2
     */
    public Plataforma2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pila = new javax.swing.JButton();
        cable1 = new javax.swing.JProgressBar();
        cable8 = new javax.swing.JProgressBar();
        cable2 = new javax.swing.JProgressBar();
        cable3 = new javax.swing.JProgressBar();
        cable7 = new javax.swing.JProgressBar();
        cable6 = new javax.swing.JProgressBar();
        cable4 = new javax.swing.JProgressBar();
        cable5 = new javax.swing.JProgressBar();
        luz2 = new javax.swing.JLabel();
        luz1 = new javax.swing.JLabel();
        luz3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        calcular = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pila.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/pila.png"))); // NOI18N
        pila.setToolTipText("Encender");
        pila.setBorderPainted(false);
        pila.setContentAreaFilled(false);
        pila.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pila.setFocusPainted(false);
        getContentPane().add(pila, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 50, -1));

        cable1.setBackground(new java.awt.Color(102, 102, 102));
        cable1.setForeground(new java.awt.Color(255, 255, 0));
        cable1.setOrientation(1);
        getContentPane().add(cable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 88, 6, 90));

        cable8.setBackground(new java.awt.Color(102, 102, 102));
        cable8.setForeground(new java.awt.Color(255, 255, 0));
        cable8.setOrientation(1);
        getContentPane().add(cable8, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 266, 6, 90));

        cable2.setBackground(new java.awt.Color(102, 102, 102));
        cable2.setForeground(new java.awt.Color(255, 255, 0));
        getContentPane().add(cable2, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 76, 228, 6));

        cable3.setBackground(new java.awt.Color(102, 102, 102));
        cable3.setForeground(new java.awt.Color(255, 255, 0));
        getContentPane().add(cable3, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 76, 240, 6));

        cable7.setBackground(new java.awt.Color(102, 102, 102));
        cable7.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(cable7, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 362, 229, 6));

        cable6.setBackground(new java.awt.Color(102, 102, 102));
        cable6.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(cable6, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 362, 240, 6));

        cable4.setBackground(new java.awt.Color(102, 102, 102));
        cable4.setForeground(new java.awt.Color(102, 102, 102));
        cable4.setOrientation(1);
        getContentPane().add(cable4, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 88, 6, 100));

        cable5.setBackground(new java.awt.Color(102, 102, 102));
        cable5.setForeground(new java.awt.Color(102, 102, 102));
        cable5.setOrientation(1);
        getContentPane().add(cable5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 6, 100));

        luz2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icono2.png"))); // NOI18N
        getContentPane().add(luz2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 80, 60));

        luz1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icono2.png"))); // NOI18N
        getContentPane().add(luz1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 60, 90));

        luz3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icono2.png"))); // NOI18N
        getContentPane().add(luz3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 80, 80));

        jLabel7.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("I total");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        jLabel12.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("V total");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        jLabel11.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("R total");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("I3");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, -1, -1));

        jLabel2.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("I2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, -1, -1));

        jLabel3.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("V3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, -1, -1));

        jLabel4.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("I1");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("V1");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        jLabel6.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("R1");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 46, 20, 20));

        jLabel8.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("R3");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, -1));

        jLabel9.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("V2");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, -1, -1));

        jLabel10.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("R2");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, -1, -1));

        jLabel66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/t.png"))); // NOI18N
        getContentPane().add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 30, 40));

        jLabel67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/t.png"))); // NOI18N
        getContentPane().add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 30, 40));

        jLabel68.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/t.png"))); // NOI18N
        getContentPane().add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 30, 40));

        jLabel69.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/t.png"))); // NOI18N
        getContentPane().add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 30, 40));

        calcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/calc.png"))); // NOI18N
        calcular.setToolTipText("Calculadora");
        calcular.setBorderPainted(false);
        calcular.setContentAreaFilled(false);
        calcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        calcular.setFocusPainted(false);
        getContentPane().add(calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 40, 40));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/imagen.jpg"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 428));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Plataforma2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Plataforma2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Plataforma2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Plataforma2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Plataforma2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JProgressBar cable1;
    public javax.swing.JProgressBar cable2;
    public javax.swing.JProgressBar cable3;
    public javax.swing.JProgressBar cable4;
    public javax.swing.JProgressBar cable5;
    public javax.swing.JProgressBar cable6;
    public javax.swing.JProgressBar cable7;
    public javax.swing.JProgressBar cable8;
    public javax.swing.JButton calcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel luz1;
    public javax.swing.JLabel luz2;
    public javax.swing.JLabel luz3;
    public javax.swing.JButton pila;
    // End of variables declaration//GEN-END:variables
}
