/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author UsuarioN°1000
 */
public class Plataforma2 extends javax.swing.JFrame {

    /**
     * Creates new form Plataforma2
     */
    public Plataforma2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pila = new javax.swing.JButton();
        cable = new javax.swing.JProgressBar();
        cable1 = new javax.swing.JProgressBar();
        cable2 = new javax.swing.JProgressBar();
        cable3 = new javax.swing.JProgressBar();
        cable11 = new javax.swing.JProgressBar();
        cable4 = new javax.swing.JProgressBar();
        cable5 = new javax.swing.JProgressBar();
        cable6 = new javax.swing.JProgressBar();
        luz2 = new javax.swing.JLabel();
        luz3 = new javax.swing.JLabel();
        luz4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        calcular = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(686, 428));
        setPreferredSize(new java.awt.Dimension(686, 428));
        getContentPane().setLayout(null);

        pila.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/pila.png"))); // NOI18N
        pila.setBorderPainted(false);
        pila.setContentAreaFilled(false);
        pila.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pila.setFocusPainted(false);
        getContentPane().add(pila);
        pila.setBounds(12, 184, 96, 82);

        cable.setBackground(new java.awt.Color(102, 102, 102));
        cable.setForeground(new java.awt.Color(255, 255, 0));
        cable.setOrientation(1);
        getContentPane().add(cable);
        cable.setBounds(57, 88, 6, 90);

        cable1.setBackground(new java.awt.Color(102, 102, 102));
        cable1.setForeground(new java.awt.Color(255, 255, 0));
        cable1.setOrientation(1);
        getContentPane().add(cable1);
        cable1.setBounds(56, 266, 6, 90);

        cable2.setBackground(new java.awt.Color(102, 102, 102));
        cable2.setForeground(new java.awt.Color(255, 255, 0));
        getContentPane().add(cable2);
        cable2.setBounds(57, 76, 228, 6);

        cable3.setBackground(new java.awt.Color(102, 102, 102));
        cable3.setForeground(new java.awt.Color(255, 255, 0));
        getContentPane().add(cable3);
        cable3.setBounds(304, 76, 240, 6);

        cable11.setBackground(new java.awt.Color(102, 102, 102));
        cable11.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(cable11);
        cable11.setBounds(56, 362, 229, 6);

        cable4.setBackground(new java.awt.Color(102, 102, 102));
        cable4.setForeground(new java.awt.Color(255, 255, 0));
        getContentPane().add(cable4);
        cable4.setBounds(304, 362, 240, 6);

        cable5.setBackground(new java.awt.Color(102, 102, 102));
        cable5.setForeground(new java.awt.Color(255, 255, 0));
        cable5.setOrientation(1);
        getContentPane().add(cable5);
        cable5.setBounds(538, 88, 6, 100);

        cable6.setBackground(new java.awt.Color(102, 102, 102));
        cable6.setForeground(new java.awt.Color(255, 255, 0));
        cable6.setOrientation(1);
        getContentPane().add(cable6);
        cable6.setBounds(538, 255, 6, 100);

        luz2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icono2.png"))); // NOI18N
        getContentPane().add(luz2);
        luz2.setBounds(505, 194, 70, 60);

        luz3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icono2.png"))); // NOI18N
        getContentPane().add(luz3);
        luz3.setBounds(260, 20, 60, 72);

        luz4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icono2.png"))); // NOI18N
        getContentPane().add(luz4);
        luz4.setBounds(260, 302, 80, 80);

        jLabel7.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("I total");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(80, 270, 40, 16);

        jLabel12.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("V total");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(90, 220, 44, 16);

        jLabel11.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("R total");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(80, 170, 44, 16);

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("I3");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(330, 320, 11, 16);

        jLabel2.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("I2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(510, 240, 12, 16);

        jLabel3.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("V3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(250, 320, 15, 16);

        jLabel4.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("I1");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(320, 50, 11, 16);

        jLabel5.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("V1");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(260, 50, 15, 16);

        jLabel6.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("R1");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(290, 90, 15, 16);

        jLabel8.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("R3");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(290, 290, 15, 16);

        jLabel9.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("V2");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(510, 180, 16, 16);

        jLabel10.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("R2");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(500, 210, 16, 16);

        jLabel66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/t.png"))); // NOI18N
        getContentPane().add(jLabel66);
        jLabel66.setBounds(50, 340, 30, 40);

        jLabel67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/t.png"))); // NOI18N
        getContentPane().add(jLabel67);
        jLabel67.setBounds(50, 60, 30, 40);

        jLabel68.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/t.png"))); // NOI18N
        getContentPane().add(jLabel68);
        jLabel68.setBounds(520, 60, 30, 40);

        jLabel69.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/t.png"))); // NOI18N
        getContentPane().add(jLabel69);
        jLabel69.setBounds(520, 340, 30, 40);

        calcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/calc.png"))); // NOI18N
        calcular.setBorderPainted(false);
        calcular.setContentAreaFilled(false);
        calcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        calcular.setFocusPainted(false);
        getContentPane().add(calcular);
        calcular.setBounds(560, 350, 82, 58);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/imagen.jpg"))); // NOI18N
        jLabel13.setPreferredSize(new java.awt.Dimension(686, 428));
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 0, 670, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Plataforma2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Plataforma2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Plataforma2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Plataforma2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Plataforma2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JProgressBar cable;
    public javax.swing.JProgressBar cable1;
    public javax.swing.JProgressBar cable11;
    public javax.swing.JProgressBar cable2;
    private javax.swing.JProgressBar cable3;
    public javax.swing.JProgressBar cable4;
    public javax.swing.JProgressBar cable5;
    public javax.swing.JProgressBar cable6;
    public javax.swing.JButton calcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel luz2;
    public javax.swing.JLabel luz3;
    public javax.swing.JLabel luz4;
    public javax.swing.JButton pila;
    // End of variables declaration//GEN-END:variables
}
