/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author UsuarioN°1000
 */
public class Welcome extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     */
    public Welcome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wevento = new javax.swing.JButton();
        wserie = new javax.swing.JButton();
        wparalelo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        wevento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ffqe.gif"))); // NOI18N
        wevento.setToolTipText("Preguntas");
        wevento.setBorder(null);
        wevento.setBorderPainted(false);
        wevento.setContentAreaFilled(false);
        wevento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        wevento.setFocusPainted(false);
        wevento.setFocusable(false);
        getContentPane().add(wevento, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 278, -1, -1));

        wserie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/p.gif"))); // NOI18N
        wserie.setToolTipText("Circuito en serie");
        wserie.setBorder(null);
        wserie.setBorderPainted(false);
        wserie.setContentAreaFilled(false);
        wserie.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        wserie.setFocusPainted(false);
        wserie.setFocusable(false);
        getContentPane().add(wserie, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 278, -1, -1));

        wparalelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/D92.gif"))); // NOI18N
        wparalelo.setToolTipText("Circuito en paralelo");
        wparalelo.setBorder(null);
        wparalelo.setBorderPainted(false);
        wparalelo.setContentAreaFilled(false);
        wparalelo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        wparalelo.setFocusPainted(false);
        wparalelo.setFocusable(false);
        getContentPane().add(wparalelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 278, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/OHM3v.png"))); // NOI18N
        jLabel4.setMaximumSize(new java.awt.Dimension(540, 260));
        jLabel4.setMinimumSize(new java.awt.Dimension(540, 260));
        jLabel4.setPreferredSize(new java.awt.Dimension(540, 260));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 530, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/imagen.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(816, 474));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JButton wevento;
    public javax.swing.JButton wparalelo;
    public javax.swing.JButton wserie;
    // End of variables declaration//GEN-END:variables
}
